# Generated by Django 3.0.3 on 2020-03-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulos',
            new_name='Articles',
        ),
        migrations.RenameModel(
            old_name='Pedidos',
            new_name='Orders',
        ),
    ]
