# Generated by Django 3.0.3 on 2020-03-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManager', '0002_auto_20200304_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
